version: '3.8'

services:
  roadrunner-skeleton:
    image: roadrunner-skeleton
    hostname: roadrunner
    build:
      context: roadrunner
      args:
        RR_VERSION: ${RR_VERSION}
        PHP_IMAGE: ${PHP_IMAGE}
    ports:
      - "8080:8080"
    environment:
      - RR_VERSION=${RR_VERSION}
      - HISTFILE=/home/utente/shell_history/.x_history
    working_dir: /app
    volumes:
      - ../:/app:delegated
      - ../config/.rr.yaml:/etc/rr.yaml
      - ./data/shell_history:/home/utente/shell_history